# Basic Clipperplus Tests

In [19]:
import numpy as np
import clipperpluspy
import unittest

In [20]:
class TestClipperplus(unittest.TestCase):
    
    test_data = [
        {"name": "Adjacency Matrix 1",
         "adj": np.array([[0, 0, 1, 1, 1, 1, 1, 0, 1, 0],
                          [0, 0, 1, 1, 1, 0, 1, 1, 1, 1],
                          [1, 1, 0, 1, 0, 1, 1, 1, 0, 1],
                          [1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
                          [1, 1, 0, 1, 0, 0, 1, 1, 1, 1],
                          [1, 0, 1, 1, 0, 0, 1, 1, 1, 1],
                          [1, 1, 1, 1, 1, 1, 0, 1, 1, 0],
                          [0, 1, 1, 1, 1, 1, 1, 0, 1, 1],
                          [1, 1, 0, 1, 1, 1, 1, 1, 0, 1],
                          [0, 1, 1, 1, 1, 1, 0, 1, 1, 0]]),
         "expected_clique_size": 6,
         "expected_clique": [1, 3, 4, 6, 7, 8],
         "expected_certificate": 0},
        {"name": "Adjacency Matrix 2",
         "adj": np.array([[0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
                          [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
                          [1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
                          [1, 1, 1, 0, 1, 1, 1, 0, 1, 1],
                          [1, 1, 1, 1, 0, 1, 0, 1, 1, 0],
                          [1, 1, 1, 1, 1, 0, 1, 1, 1, 1],
                          [1, 1, 1, 1, 0, 1, 0, 1, 1, 1],
                          [1, 1, 1, 0, 1, 1, 1, 0, 1, 1],
                          [1, 1, 1, 1, 1, 1, 1, 1, 0, 1],
                          [1, 1, 1, 1, 0, 1, 1, 1, 1, 0]]),
         "expected_clique_size": 7,
         "expected_clique": [6, 0, 2, 3, 5, 8, 9],
         "expected_certificate": 3},
        {"name": "Adjacency Matrix 3",
         "adj": np.array([[0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1],
                          [0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1],
                          [1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0],
                          [0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1],
                          [0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
                          [1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1],
                          [1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
                          [1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                          [0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0],
                          [0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1],
                          [1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1],
                          [1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1],
                          [0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1],
                          [1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1],
                          [1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
                          [1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0],
                          [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0],
                          [1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
                          [0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1],
                          [1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0]]),
         "expected_clique_size": 8,
         "expected_clique": [4, 10, 13, 14, 15, 16, 17, 18],
         "expected_certificate": 0}
    ]
    def test_clique(self):
        for i in range(len(self.test_data)):
            with self.subTest("Finding cliques on predetermined adjacency matrices", i=i):
                adj = self.test_data[i]["adj"]
                clique_size, clique, certificate = clipperpluspy.clipperplus_clique(adj)
                print(f"\nTest {i}: {self.test_data[i]['name']}\n")
                print(f"{self.test_data[i]['adj']}\n", flush=True)
                self.assertEqual(clique_size, self.test_data[i]["expected_clique_size"])
                self.assertEqual(clique, self.test_data[i]["expected_clique"])
                self.assertEqual(certificate, self.test_data[i]["expected_certificate"])
                print(flush=True)

In [21]:
unittest.main(argv=[''], verbosity=2, exit=False)

test_clique (__main__.TestClipperplus) ... 


Test 0: Adjacency Matrix 1

[[0 0 1 1 1 1 1 0 1 0]
 [0 0 1 1 1 0 1 1 1 1]
 [1 1 0 1 0 1 1 1 0 1]
 [1 1 1 0 1 1 1 1 1 1]
 [1 1 0 1 0 0 1 1 1 1]
 [1 0 1 1 0 0 1 1 1 1]
 [1 1 1 1 1 1 0 1 1 0]
 [0 1 1 1 1 1 1 0 1 1]
 [1 1 0 1 1 1 1 1 0 1]
 [0 1 1 1 1 1 0 1 1 0]]

number of graph nodes: 10
number of graph edges: 37
kcores.size(): 11
core_numbers.size(): 10
max clique kcore bound: 7
core numbers: 6 6 6 6 6 6 6 6 6 6 
running find_heuristic_clique...
heuristic found clique of size: 5
heuristic clique: 0 2 3 5 6 
colors: 1 1 2 3 2 4 5 6 7 5 
max clique chromatic bound: 7
time for heuristic clique & core numbers: 2.9e-05
pruning graph...
idx_keep: 0 1 2 3 4 5 6 7 8 9 
idx_prune: 
time for graph pruning: 1.6e-05
clipper time: u0, d set up: 3e-06
clipper: u0: 0 0.447214 0 0 0.447214 0 0 0.447214 0.447214 0.447214 
clipper: u: 0.145865 0.364662 0.218797 0.364662 0.364662 0.218797 0.29173 0.364662 0.364662 0.364662 
clipper: initial d: 1.8
clipper: params_.tol_u: 1e-08
clipper: params_.tol_F: 1e-0

ok

----------------------------------------------------------------------
Ran 1 test in 0.011s

OK


s: 20
clipper time: optimization: 0.000108
d: 3428.58
ksum: 103
jsum: 190
i: 10
clipper: u final: 0 0 0 0 0.353553 0 0 0 0 0 0.353553 0 0 0.353553 0.353553 0.353553 0.353553 0.353553 0.353553 0 
clipper: rounding_thresh: 1e-09
clipper: nodes above eps thresh: 4 10 13 14 15 16 17 18 
clipper time: rounding output: 4.7e-05
clipper's clique size: 8
clipper's solution:4 10 13 14 15 16 17 18 
time for clipper optimization: 0.000176
optim-based clique: 4 10 13 14 15 16 17 18 
optimization gave better or equal clique

could not certify max clique
time for certification: 6e-06
